#!/usr/bin/env python3

"""A script to merge different modules of the
EASE ontology into a bundled one file version.
"""

__author__ = "Daniel Beßler"
__license__ = "GPL"
__version__ = "1.0.0"
__maintainer__ = "Daniel Beßler"
__email__ = "danielb@cs.uni-bremen.de"

# TODO: write me
